### ISSUE TITLE
Page styles, css and images not rendering

### ISSUE THREAD

**Issue by LaurelineP** [Nevin06/Nevin06.github.io#1]
[Hint](https://expressjs.com/en/starter/static-files.html): when you are using express to build your server, 
🔹the regular relative paths is not sufficient
🔹 to express the server to get static files you have to use a middleware
All the answers are there 🙂 I let you try then you tell me 🙂 
Keep me in the loop if you want.

**Comment by Nevin06** [comment]
To serve static files such as images, CSS files, and JavaScript files, I used the **_express.static_** built-in middleware function in Express.

https://github.com/Nevin06/Nevin06.github.io/assets/18488402/387a43a0-d130-4abf-a797-26c9e192480a


`// Serve static files from the 'Nevin06.github.io' directory in app.js file
app.use(express.static('Nevin06.github.io'));`

**Comment by LaurelineP** [comment]
Happy you've found your way through it :) 🙌🚀
